@baseUrl = http://localhost:5000
##################################################


################################################## Passwords
GET {{baseUrl}}/api/Passwords?search=abc
#####
POST {{baseUrl}}/api/Passwords
Content-type: application/json

{
   "id": 1,
   "website": "abc",
   "username": "abc",
   "encryptedPassword": "abc"
}
#####
